# Generated by Django 5.1.5 on 2025-02-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug')], default='Task', max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10)),
                ('estimated_time', models.FloatField(help_text='Estimated time in hours')),
                ('actual_time_taken', models.FloatField(blank=True, help_text='Actual time taken in hours', null=True)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('Commited', 'Commited'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Defer', 'Defer')], default='Defer', max_length=15)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_link', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dailytask.user')),
            ],
        ),
    ]
