# Generated by Django 5.1.5 on 2025-02-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0002_alter_task_priority_alter_task_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_time_taken',
            field=models.CharField(blank=True, help_text='Actual time taken in hours', max_length=255, null=True),
        ),
    ]
