# Generated by Django 5.1.5 on 2025-02-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0003_alter_task_actual_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
