# Generated by Django 5.1.5 on 2025-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0004_alter_task_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
