# Generated by Django 5.1.5 on 2025-02-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0008_alter_task_priority_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('To-Do', 'To-Do'), ('Commited', 'Commited'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Defer', 'Defer')], default='To-Do', max_length=15, null=True),
        ),
    ]
