# Generated by Django 5.1.5 on 2025-02-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytask', '0010_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(blank=True, help_text='Estimated time in hours', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('High', 'High'), ('Critical', 'Critical')], default='Low ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('To-Do', 'To-Do'), ('Commited', 'Commited'), ('In-Progress', 'InProgress'), ('Completed', 'Completed'), ('Defer', 'Defer')], default='To-Do', max_length=15, null=True),
        ),
    ]
