"""
Django settings for attendence project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.version_info = (1, 4, 6, 'final', 0)
pymysql.install_as_MySQLdb()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i(6)%tykxb6$cuy63frlpmk(^=a^dpwm%i_k$gncz4=$-!5e@-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

ALLOWED_HOSTS = ['192.168.1.36','1141-2409-408d-1e97-8a8-44c9-fcb4-52ef-2579.ngrok-free.app','127.0.0.1','localhost']
CORS_ALLOWED_ORIGINS = [
    'https://1141-2409-408d-1e97-8a8-44c9-fcb4-52ef-2579.ngrok-free.app ',
    'https://ab54-59-97-51-97.ngrok-free.app',
    'http://192.168.1.33:8082',
    'https://6628-59-97-51-97.ngrok-free.app',
    'https://codingboss.in',
    'https://www.codingboss.in',
    'https://api.codingboss.in',
    'http://api.codingboss.in',
    'http://api.codingboss.in',
    'https://www.codingboss.in',
    'https://www.codingboss.in',
    'https://api-dev.thiran360ai.com',
    'http://192.168.1.240:8899',
    'https://dev.thiran360ai.com',
    'https://25db-59-97-51-97.ngrok-free.app',                    
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://localhost:3003',
    'http://localhost:3004',
    'http://59.97.51.97:8081',
    'http://localhost:8090',
    'https://thiran360ai.github.io',
    # 'https://thiran360ai.github.io/capture360Admin/manifest.json',
    # 'file:///D:/26/ne.html',
    'http://127.0.0.1',
    'http://127.0.0.1:8080',
    # 'http://ngrok-skip-browser-warning',  # Add scheme and netloc for 'ngrok-skip-browser-warning'
    'https://gokulrajalp.github.io',
    'http://192.168.1.3'
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'accept',
    'origin',
    'x-requested-with',
]

# Allow credentials (if needed)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dailytask',
    'rest_framework',
    

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'attendence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendence.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'attendance_db',
        'USER': 'root',
        'PASSWORD': 'tenyson',
        'HOST': 'localhost', 
        'PORT': '3306',
    
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


